[package]
authors = ['Phala Network']
edition = '2018'
name = 'pallet-phala'
version = "3.1.0"
license = "Apache 2.0"
homepage = "https://phala.network/"
repository = "https://github.com/Phala-Network/phala-blockchain"

[package.metadata.docs.rs]
targets = ["x86_64-unknown-linux-gnu"]

[dependencies]
serde = { version = "1.0.101", default-features = false, optional = true }
codec = { package = "parity-scale-codec", version = "1.3.4", default-features = false }
frame-support = { version = "2.0.0", default-features = false, path = "../../substrate/frame/support" }
frame-system = { version = "2.0.0", default-features = false, path = "../../substrate/frame/system" }
pallet-randomness-collective-flip = { version = "2.0.0", default-features = false, path = "../../substrate/frame/randomness-collective-flip"}
sp-runtime = { version = "2.0.0", default-features = false, path = "../../substrate/primitives/runtime" }
sp-std = { version = "2.0.0", default-features = false, path = "../../substrate/primitives/std" }
sp-io = { version = "2.0.0", default-features = false, path = "../../substrate/primitives/io" }
sp-core = { version = "2.0.0", default-features = false, path = "../../substrate/primitives/core" }
frame-benchmarking = { version = "2.0.0", default-features = false, path = "../../substrate/frame/benchmarking", optional = true }

pallet-balances = { version = "2.0.0", default-features = false, path = "../../substrate/frame/balances" }

phala-types = { default-features = false, path = "../../common/types" }
chrono = { version = "0.4", default-features = false }
itertools = { version = "0.8", default-features = false }
untrusted = { version = "0.7" }
base64 = { version = "0.11", default-features = false, features = ["alloc"] }
hex = { version = "0.4", default-features = false }
webpki = { path = "../../webpki", default-features = false }
serde_json = { version = "1.0.41", default-features = false, features = ["alloc"] }
blake2-rfc = { version = "0.2.18", default-features = false }

[dev-dependencies]
assert_matches = "1.4.0"
pallet-timestamp = { version = "2.0.0", path = "../../substrate/frame/timestamp" }
hex-literal = "0.3.1"
libsecp256k1 = { version = "0.3.2", default-features = false }
rand = "0.7.3"

[features]
default = ['std']
std = [
    "serde/std",
    "codec/std",
    "sp-runtime/std",
    "frame-support/std",
    "frame-system/std",
    "sp-io/std",
    "sp-std/std",
    "sp-core/full_crypto",
    "frame-benchmarking/std"
]
test = [
    "sp-core/full_crypto"
]
runtime-benchmarks = ["frame-benchmarking"]
